---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: ccd-service
  namespace: ccfd
  labels:
    app: ccd-service
    app.kubernetes.io/part-of: PAM
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - ccd-service
        from:
          kind: ImageStreamTag
          namespace: ccfd
          name: 'ccd-service:1.0-SNAPSHOT'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    app: ccd-service
    deploymentconfig: ccd-service
  template:
    metadata:
      labels:
        app: ccd-service
        deploymentconfig: ccd-service
    spec:
      containers:
        - name: ccd-service
          image: ruivieira/ccd-service
          ports:
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
            - containerPort: 9779
              protocol: TCP
          env:
            - name: BROKER_URL
              value: 'odh-message-bus-kafka-brokers:9092'
            - name: CUSTOMER_NOTIFICATION_TOPIC
              value: ccd-customer-outgoing
            - name: NEXUS_URL
              value: 'http://nexus:8081'
            - name: SELDON_URL
              value: 'ccfd-seldon-usertask-model:5000'
            - name: M2_HOME
              value: '/.m2'
            - name: JAVA_OPTS
              value: '-Dorg.jbpm.task.prediction.service=SeldonPredictionService'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: ccd-service
  namespace: ccfd
  labels:
    app: ccd-service
spec:
  ports:
    - name: 8090-tcp
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    - name: 9779-tcp
      protocol: TCP
      port: 9779
      targetPort: 9779
  selector:
    app: ccd-service
    deploymentconfig: ccd-service
status:
  loadBalancer: {}
---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ccd-service
  namespace: ccfd
  labels:
    app: ccd-service
spec:
  lookupPolicy:
    local: false
  tags:
    - name: 1.0-SNAPSHOT
      annotations:
        openshift.io/imported-from: 'ruivieira/ccd-service:1.0-SNAPSHOT'
      from:
        kind: DockerImage
        name: 'ruivieira/ccd-service:1.0-SNAPSHOT'
      generation: 2
      importPolicy: {}
      referencePolicy:
        type: Source
